## no longer required because we now dynamically get the routes from the controller
#content_get:
#    pattern: /{id}.{_format}
#    defaults: { _controller: StarterRestApiBundle:Content:getContent, _format: json }
#    methods: GET
#    requirements:
#        id: \d+

## no longer required because we now dynamically get the routes from the controller
#contents_get:
#    pattern: .{_format}
#    defaults: { _controller: StarterRestApiBundle:Content:getContents, _format: json }
#    methods: GET
