services:
    starter.app_bundle.content_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Starter\AppBundle\Entity\Content

    starter.app_bundle.content_dispatcher:
        class: Starter\Content\Dispatcher\ContentDispatcher
        arguments:
            - @starter.app_bundle.content_repository
            - @starter.app_bundle.form.handler.content_form_handler

    starter.app_bundle.content_provider:
        class: Starter\Content\Provider\ContentProvider
        arguments:
            - @starter.app_bundle.content_repository
            - @starter.app_bundle.form.handler.content_form_handler

    # http://symfony.com/doc/current/book/forms.html#defining-your-forms-as-services
    starter.app_bundle.form.type.content:
        class: Starter\Content\Form\Type\ContentType
        tags:
            - { name: form.type, alias: content_form }

    starter.app_bundle.form.handler.content_form_handler:
        class: Starter\AppBundle\Form\Handler\FormHandler
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @starter.app_bundle.form.type.content