# view all routes: app/console debug:router
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

rest_api:
    type:     rest
    resource: "@StarterRestApiBundle/Resources/config/routing.yml"
    prefix:   /api